name: Setup Bun
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  setup-bun:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        bun-version:
          - latest
          - canary
          - "0.5.6"
          - "0.5.x"
          - ">=0.5.7"
          - "9be68ac2350b965037f408ce4d47c3b9d9a76b63"
        baseline:
          - "true"
          - "false"
        profile:
          - "true"
          - "false"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: ./
        with:
          bun-version: ${{ matrix.bun-version }}
          baseline: ${{ matrix.baseline }}
          profile: ${{ matrix.profile }}
      - id: verify-bun
        name: Verify Bun
        run: |
          which bun
          which bunx
          bun --version
